### PR TITLE
feat: clone conda-store environment

### PR DESCRIPTION
**Pull request by gabalafou**
Closes Quansight/conda-store#142

### CODE REVIEW

**Comment by gabalafou** [comment]
See notes/discussion at https://github.com/Quansight/gator/pull/36

**Comment by fcollonval** [comment]
Kicking the CI

**Comment by fcollonval** [comment]
Do you mind rebasing the PR on master @gabalafou ?

**Comment by fcollonval** [comment]
Kicking the CI

**Comment by fcollonval** [comment]
Ok now we get useful CI (except test on Windows that you can ignore for now).

It seems your code need linting. Could you run `jlpm run eslint` and commit the changes please?

**Comment by fcollonval** [comment]
Thanks for rebasing

This PR has a linter issue. Would you mind running `jlpm eslint` locally and publish the changes?

**Review by fcollonval — APPROVED** [review]
Thanks @gabalafou

**Pull request merged**
