### PR TITLE
Mamba not recognized on windows

### LINKED ISSUE #119: Mamba not recognized on windows
## Description

The command used for detecting the version of mamba is not working on Windows:

```py
from subprocess import Popen, PIPE

Popen(["mamba", "--version"], stdout=PIPE, stderr=PIPE).communicate()
```

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-8405acab7e6e> in <module>()
      1 from subprocess import Popen, PIPE
      2 
----> 3 Popen(["conda", "--version"], stdout=PIPE, stderr=PIPE).communicate()

C:\Users\freud\Miniconda3\envs\gator\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

C:\Users\freud\Miniconda3\envs\gator\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #119

### CODE REVIEW

**Comment by fcollonval** [comment]
@jtpio could you try that this PR does not break the dependency graph on non-Windows computer?

In WSL, it works. But on binder it seems to hit a bug:

```
Traceback (most recent call last):\n  File "/srv/conda/envs/notebook/bin/mamba", line 7, in <module>\n    from mamba.mamba import main\n  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/mamba/mamba.py", line 52, in <module>\n    import mamba.mamba_api as api\nImportError: libiconv.so.2: cannot open shared object file: No such file or directory\n
```

**Comment by jtpio** [comment]
Thanks @fcollonval, will do.

I remember seeing this error some time before, but that was on CI with Windows.

**Comment by jtpio** [comment]
I don't seem be hitting this error locally.

However I don't seem to be able to see the graph either, after pulling this branch and setting up the environment with the following:

```bash
mamba create -n gator-tmp -c conda-forge jupyterlab=2 nodejs python -y
conda activate gator-tmp
gh pr checkout 120
pip install -e .
jupyter nbextension install mamba_gator --py --sys-prefix --symlink
jupyter nbextension enable mamba_gator --py --sys-prefix
jupyter serverextension enable mamba_gator --py --sys-prefix

yarn install
yarn run build:dev
jupyter labextension link packages/common/ packages/labextension/
```

**Comment by jtpio** [comment]
> However I don't seem to be able to see the graph either,

This seems to also be the case when opening the current master on Binder:

image

**Comment by fcollonval** [comment]
Thanks for testing Jeremy.

On the current master on Binder, the problem is the binder issue with mamba:

image

Regarding your local installation, for now the PR from @hbcarlos included the graph feature by clicking on the installed version of a package (no icon in the toolbar, nor graph for not installed package). Could you confirm that even that is not working on your computer? Could you see if `mamba --version` is raising an error?

**Comment by jtpio** [comment]
> On the current master on Binder, the problem is the binder issue with mamba:

Ah right, I missed that.

Locally:

```bash
$ mamba --version
mamba 0.7.1
conda 4.9.2
```

**Comment by jtpio** [comment]
Since `mamba` is already available on Binder, maybe we can remove it from the `environment.yml`:

https://github.com/mamba-org/gator/blob/60e900a9b86cd8b2de7f1af2839c0808ff3741de/binder/environment.yml#L7

**Comment by jtpio** [comment]
Locally, clicking on the package seems to tick the checkbox on and off:

graph-local

**Comment by jtpio** [comment]
Ah I missed that it was on the version number. Seems to be working fine locally!

image

**Comment by jtpio** [comment]
> On the current master on Binder, the problem is the binder issue with mamba:

Should be fixed in https://github.com/mamba-org/gator/pull/121

**Comment by fcollonval** [comment]
Thanks a lot for correcting Binder and for testing @jtpio.

Once merged, I'll do a release.

**Pull request merged**
