### PR TITLE
Use navigator in the classical notebook

### PR DESCRIPTION
**Pull request by fcollonval**
Address item 4 of https://github.com/mamba-org/gator/issues/88#issuecomment-721679209

> This build on top of #95 

After thinking a bit more about it, as the classical notebook is based on tab views and that the navigator provide an standalone usable view, I decided to drop the classical notebook code to only keep link opening the navigator.

One frontend to rule them all 💍 😉 

What do you think @jtpio ?

### CODE REVIEW

**Comment by jtpio** [comment]
Nice!

> One frontend to rule them all 

Yes that's pretty much the idea. In general this could be a good way for packages that used to ship both classic and lab extensions to transition to a single code base. Using modern JS / TS and tooling.

**Comment by jtpio** [comment]
> I decided to drop the classical notebook code to only keep link opening the navigator.

So that means skipping the warning step?

**Comment by fcollonval** [comment]
> So that means skipping the warning step?

The legacy integration is:

legacy_nb_integration

This PR proposal:

classical_nb_integration

As the entry points are the same between the legacy and this PR integration, I propose to skip the warning step.

**Comment by jtpio** [comment]
Looks good!

**Pull request merged**
